# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from axes import PlotCanvas

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(110, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 1)
        self.plotWidget = MyStaticMplCanvas(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setObjectName("plotWidget")
        self.gridLayout.addWidget(self.plotWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_load_event = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("view/img/appointment-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_load_event.setIcon(icon)
        self.action_load_event.setObjectName("action_load_event")
        self.action_select_new_track = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("view/img/insert-link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_select_new_track.setIcon(icon1)
        self.action_select_new_track.setObjectName("action_select_new_track")
        self.action_delete_track = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("view/img/im-kick-user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_delete_track.setIcon(icon2)
        self.action_delete_track.setObjectName("action_delete_track")
        self.action_add_hits_to_track = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("view/img/contact-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_add_hits_to_track.setIcon(icon3)
        self.action_add_hits_to_track.setObjectName("action_add_hits_to_track")
        self.action_remove_hits = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("view/img/list-remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_remove_hits.setIcon(icon4)
        self.action_remove_hits.setObjectName("action_remove_hits")
        self.action_fit_track = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("view/img/graph-2-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_fit_track.setIcon(icon5)
        self.action_fit_track.setObjectName("action_fit_track")
        self.toolBar.addAction(self.action_load_event)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_delete_track)
        self.toolBar.addAction(self.action_select_new_track)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_add_hits_to_track)
        self.toolBar.addAction(self.action_remove_hits)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_fit_track)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Selected tracks"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_load_event.setText(_translate("MainWindow", "Load Event"))
        self.action_load_event.setToolTip(_translate("MainWindow", "Load Event"))
        self.action_select_new_track.setText(_translate("MainWindow", "Select new track"))
        self.action_select_new_track.setToolTip(_translate("MainWindow", "Select new track"))
        self.action_delete_track.setText(_translate("MainWindow", "Delete track"))
        self.action_delete_track.setToolTip(_translate("MainWindow", "Delete track"))
        self.action_add_hits_to_track.setText(_translate("MainWindow", "Add hits to track"))
        self.action_add_hits_to_track.setToolTip(_translate("MainWindow", "Add hits to track"))
        self.action_remove_hits.setText(_translate("MainWindow", "Remove hits"))
        self.action_remove_hits.setToolTip(_translate("MainWindow", "Remove hits"))
        self.action_fit_track.setText(_translate("MainWindow", "Fit track"))
        self.action_fit_track.setToolTip(_translate("MainWindow", "Fit track"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

